/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author LENOVO
 */
public class ViewRFC extends javax.swing.JFrame {

    /**
     * Creates new form ViewRFC
     */
    public ViewRFC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_nombre = new javax.swing.JLabel();
        jl_appaterno = new javax.swing.JLabel();
        jl_apmaterno = new javax.swing.JLabel();
        jl_dia = new javax.swing.JLabel();
        jl_mes = new javax.swing.JLabel();
        jl_anio = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jtf_appaterno = new javax.swing.JTextField();
        jtf_apmaterno = new javax.swing.JTextField();
        jtf_dia = new javax.swing.JTextField();
        jtf_mes = new javax.swing.JTextField();
        jtf_anio = new javax.swing.JTextField();
        jb_pedir_rfc = new javax.swing.JButton();
        jl_rfc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jl_nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_nombre.setForeground(new java.awt.Color(51, 51, 51));
        jl_nombre.setText("Nombre");

        jl_appaterno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_appaterno.setText("Apellido paterno");

        jl_apmaterno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_apmaterno.setText("Apellido materno");

        jl_dia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_dia.setText("Dia nacimiento");

        jl_mes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_mes.setText("Mes nacimiento");

        jl_anio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_anio.setText("Año nacimiento");

        jtf_nombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jtf_appaterno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jtf_apmaterno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jtf_dia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jtf_mes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jtf_anio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jb_pedir_rfc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_pedir_rfc.setText("Pedir RFC");

        jl_rfc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jl_rfc.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_nombre)
                            .addComponent(jl_appaterno)
                            .addComponent(jl_apmaterno)
                            .addComponent(jl_dia)
                            .addComponent(jl_mes)
                            .addComponent(jl_anio))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_nombre)
                            .addComponent(jtf_appaterno)
                            .addComponent(jtf_apmaterno)
                            .addComponent(jtf_dia)
                            .addComponent(jtf_mes)
                            .addComponent(jtf_anio, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jb_pedir_rfc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jl_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_appaterno)
                    .addComponent(jtf_appaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_apmaterno)
                    .addComponent(jtf_apmaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_dia)
                    .addComponent(jtf_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_mes)
                    .addComponent(jtf_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_anio)
                    .addComponent(jtf_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jl_rfc)
                .addGap(36, 36, 36)
                .addComponent(jb_pedir_rfc)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRFC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jb_pedir_rfc;
    public javax.swing.JLabel jl_anio;
    public javax.swing.JLabel jl_apmaterno;
    public javax.swing.JLabel jl_appaterno;
    public javax.swing.JLabel jl_dia;
    public javax.swing.JLabel jl_mes;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JLabel jl_rfc;
    public javax.swing.JTextField jtf_anio;
    public javax.swing.JTextField jtf_apmaterno;
    public javax.swing.JTextField jtf_appaterno;
    public javax.swing.JTextField jtf_dia;
    public javax.swing.JTextField jtf_mes;
    public javax.swing.JTextField jtf_nombre;
    // End of variables declaration//GEN-END:variables
}
